config/routes.rb
Project::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users
  resources :news, :only => [:index, :show]
  resources :articles, :only => [:index, :show]
  resources :questions, :only => [:new, :create]
  resources :trademarks, :only => [:new, :create]

  match "/calculator/" => "application#calculator_form", :as => 'calculator_form'
  match "/request/" => "trademarks#new", :as => 'request_form'
  match "/contact/" => "questions#new", :as => 'contact_form'
  match "/:slug/" => "pages#show"
  root :to => "pages#show"

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :subtitle, :content, :see_also
end

app/models/chunk.rb
class Chunk < ActiveRecord::Base
  attr_accessible :title, :code, :content, :visible
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/system/attachments/:id/:filename",
                    :path => ":rails_root/public/system/attachments/:id/:filename"

  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end

end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/system/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/system/pictures/:id/:style_:basename.:extension",
                      :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_presence :data

  def url_content
    url(:content)
  end

end

app/models/news.rb
class News < ActiveRecord::Base
  default_scope :order => 'date DESC'
  attr_accessible :title, :date, :content, :of_company, :special, :comment, :see_also

  def has_comment
    self.comment and self.comment.strip.length > 0
  end
  def has_see_also
    self.see_also and self.see_also.strip.length > 0
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :title, :slug, :content, :service, :info
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :name, :email, :message
end

app/models/trademark.rb
# -*- coding: utf-8 -*-
class Trademark < ActiveRecord::Base
  attr_accessible :title, :research, :research_limit, :registration_limit, :service, :mktu, :comments, :name, :requisites, :email, :phone, :contact, :title_image, :title_mixed, :requisites_file

  validates :registration_limit, :presence => true
  validates :service, :presence => true
  validates :name, :presence => true
  validates :requisites, :presence => true
  validates :email, :presence => true
  validates :phone, :presence => true
  validates :contact, :presence => true

  has_attached_file :title_image
  has_attached_file :title_mixed
  has_attached_file :requisites_file

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,# :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :email_notifications

  scope :emailable, where(:email_notifications => true)
end

app/controllers/application_controller.rb
# -*- coding: utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale, :set_context

  def set_context
    @news_all = News.where('of_company = False').limit(3)
    @news_company = News.where('of_company = True').limit(3)

    ['header_quote','header_phones','left_announce','left_in_process','left_clients','right_social','membership','footer_copyright','footer_phones','menu'].each do |var_name|
      chunk = Chunk.find_by_code(var_name)
      if chunk and chunk.visible
        chunk = chunk.content.html_safe
      else
        chunk = ''
      end
      self.instance_variable_set('@' + var_name, chunk)
    end

  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def calculator_form
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @news = News.find(params[:id])
    @news_prev = News.find(:first, :conditions => ["date < ?", @news.date])
    @news_next = News.find(:first, :conditions => ["date > ?", @news.date])

    respond_to do |format|
      format.html # show.html.erb
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find_by_slug(params[:slug] || '') || not_found

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions/new
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # POST /questions
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        User.emailable.each do |user|
          UserMailer.new_question(user, @question).deliver
        end
        format.html { render action: "success" }
      else
        format.html { render action: "new" }
      end
    end
  end

  def success
  end

end

app/controllers/trademarks_controller.rb
class TrademarksController < ApplicationController
  # GET /trademarks/new
  def new
    @trademark = Trademark.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # POST /trademarks
  def create
    @trademark = Trademark.new(params[:trademark])

    respond_to do |format|
      if @trademark.save
        User.emailable.each do |user|
          UserMailer.new_trademark(user, @trademark, request).deliver
        end
        format.html { render action: "success" }
      else
        format.html { render action: "new" }
      end
    end
  end

  def success
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chunks_helper.rb
module ChunksHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/trademarks_helper.rb
module TrademarksHelper
end

app/views/application/calculator.html.erb
<% content_for :title do %>Калькулятор<% end %>

<% content_for :content do %>

<p style="font-size:14px; font-family:tahoma; color:#000000; margin-left: 10px; margin: 50px 7px 7px 15px;"><b>Калькулятор:</b><br><br></p>

<form method="post" enctype="multipart/form-data" action="/oncalc.html#rslclc" style="font-size:14px; font-family:tahoma; color:#000000; margin-left: 10px; margin: 0px 7px 7px 15px;">
    <select name="selCalc" id="selCalc">
        <option value="0" selected="selected">Вид услуги</option>
        <option value="1" >Регистрация товарного знака</option>
        <option value="2">Регистрация договора уступки/ отчуждения ТЗ</option>
        <option value="3">Регистрация лицензионного договора ТЗ</option>
    </select>
<div id="calc" style="display:none; font-size:14px; font-family:tahoma; color:#000000; margin-left: 10px; margin: 50px 7px 7px 15px;">
    <form method="post" enctype="multipart/form-data" action="/oncalc.html#rslclc">
        <table width="95%" border="0" cellspacing="3" cellpadding="5">
            <tr>
                <td align="left">
                    1.Выбрать вид товарного знака:</strong></td>
                <td valign="middle" align="left" nowrap>
                    <select name="vid" id="vid">
                        <option value="1" selected="selected">Словесный</option>
                        <option value="2">Изобразительный</option>
                        <option value="3">Комбинированный</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td align="left">
                    <br>2.Количество классов МКТУ:<br>
                </td>
                <td valign="middle" align="left"><br>
                    <select name="countClass" id="countClass">
                        <option value="1" selected="selected">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                        <option value="16">16</option>
                        <option value="17">17</option>
                        <option value="18">18</option>
                        <option value="19">19</option>
                        <option value="20">20</option>
                        <option value="21">21</option>
                        <option value="22">22</option>
                        <option value="23">23</option>
                        <option value="24">24</option>
                        <option value="25">25</option>
                        <option value="26">26</option>
                        <option value="27">27</option>
                        <option value="28">28</option>
                        <option value="29">29</option>
                        <option value="30">30</option>
                        <option value="31">31</option>
                        <option value="32">32</option>
                        <option value="33">33</option>
                        <option value="34">34</option>
                        <option value="35">35</option>
                        <option value="36">36</option>
                        <option value="37">37</option>
                        <option value="38">38</option>
                        <option value="39">39</option>
                        <option value="40">40</option>
                        <option value="41">41</option>
                        <option value="42">42</option>
                        <option value="43">43</option>
                        <option value="44">44</option>
                        <option value="45">45</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td rowspan="2" align="left">
                    3.Полный патентный поиск:<br></td>
                <td valign="middle" align="left"><br><br>
                    <select name="findTrue" id="findTrue" >
                        <option value="1" selected="selected">Да</option>
                        <option value="0">Нет</option>
                    </select>&nbsp;<em>Нужен?</em>

                </td>
            </tr>
            <tr>
                <td valign="middle" align="left">
                    <select id="countFind" name="countFind">
                        <option value="1">1-2 дня</option>
                        <option value="2" selected="selected">3-4 дня</option>
                    </select>&nbsp;<em>Срок исполнения</em></td>
            </tr>
            <tr>
            <td align="left"><br>
                4.Срок регистрации ТЗ:<br></td>
            <td valign="middle" align="left"><br>
                <select name="reg" id="reg">
                    <option value="1" disabled="disabled">4-5 месяцев</option>
                    <option value="2">8-9 месяцев</option>
                    <option value="3" selected="selected">12-14 месяцев</option>
                </select>&nbsp;<em>Период времени</em>
            </td>

        </tr>
     </table>
     <p>
        <input id="buttonCalc" type="button" name="buttonCalc" value="Рассчитать">

    </p>
  </form>
  </div>

  <div id="calc2" style="display:none; font-size:14px; font-family:tahoma; color:#000000; margin-left: 10px;">
    <form method="post" enctype="multipart/form-data" action="/oncalc.html#rslclc">
        <table width="95%" border="0" cellspacing="3" cellpadding="5">
            <tr>
                <td align="left">
                    1.Количество товарных знаков в договоре:<br>
                </td>
                <td valign="middle" align="left">
                    <select name="countClass" id="countClass">
                        <option value="1" selected="selected">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                        <option value="16">16</option>
                        <option value="17">17</option>
                        <option value="18">18</option>
                        <option value="19">19</option>
                        <option value="20">20</option>
                        <option value="21">21</option>
                        <option value="22">22</option>
                        <option value="23">23</option>
                        <option value="24">24</option>
                        <option value="25">25</option>
                        <option value="26">26</option>
                        <option value="27">27</option>
                        <option value="28">28</option>
                        <option value="29">29</option>
                        <option value="30">30</option>
                        <option value="31">31</option>
                        <option value="32">32</option>
                        <option value="33">33</option>
                        <option value="34">34</option>
                        <option value="35">35</option>
                        <option value="36">36</option>
                        <option value="37">37</option>
                        <option value="38">38</option>
                        <option value="39">39</option>
                        <option value="40">40</option>
                        <option value="41">41</option>
                        <option value="42">42</option>
                        <option value="43">43</option>
                        <option value="44">44</option>
                        <option value="45">45</option>
                        <option value="46">46</option>
                        <option value="47">47</option>
                        <option value="48">48</option>
                        <option value="49">49</option>
                        <option value="50">50</option>
                        <option value="51">51</option>
                        <option value="52">52</option>
                        <option value="53">53</option>
                        <option value="54">54</option>
                        <option value="55">55</option>
                        <option value="56">56</option>
                        <option value="57">57</option>
                        <option value="58">58</option>
                        <option value="59">59</option>
                        <option value="60">60</option>
                        <option value="61">61</option>
                        <option value="62">62</option>
                        <option value="63">63</option>
                        <option value="64">64</option>
                        <option value="65">65</option>
                        <option value="66">66</option>
                        <option value="67">67</option>
                        <option value="68">68</option>
                        <option value="69">69</option>
                        <option value="70">70</option>
                        <option value="71">71</option>
                        <option value="72">72</option>
                        <option value="73">73</option>
                        <option value="74">74</option>
                        <option value="75">75</option>
                        <option value="76">76</option>
                        <option value="77">77</option>
                        <option value="78">78</option>
                        <option value="79">79</option>
                        <option value="80">80</option>
                        <option value="81">81</option>
                        <option value="82">82</option>
                        <option value="83">83</option>
                        <option value="84">84</option>
                        <option value="85">85</option>
                        <option value="86">86</option>
                        <option value="87">87</option>
                        <option value="88">88</option>
                        <option value="89">89</option>
                        <option value="90">90</option>
                    </select>
                </td>
            </tr>
            <tr>
            <td align="left">
                2.Срок регистрации<br></td>
            <td valign="middle" align="left">
                <select name="reg" id="reg">
                    <option value="1">1,5 месяца</option>
                    <option value="2" selected="selected">2 месяца</option>
                </select>&nbsp;<em>Период регистрации</em>
            </td>

        </tr>
     </table>
     <p>
        <input id="buttonCalc" type="button" name="buttonCalc" value="Рассчитать">

    </p>
  </form>
  </div>


  <div id="day" style="display:none"> дня</div>
  <div id="summa" style="display:none">
  <p style="font-size:14px; font-family:tahoma; color:#000000; margin-left: 10px;"><b><font color="red">Общая стоимость регистрации: <span id="sum"></span> рублей</font></b></p>
<p style="font-size:14px; font-family:tahoma; color:#000000; margin-left: 10px;"><b>В стоимость регистрации включено:</b></p>
<p id="usl2" style="font-size:14px;display:none; font-family:tahoma; color:#000000; margin-left: 10px;">Услуги по подготовке и подаче договора на регистрацию - <span id="uslugi2"></span> рублей</p>
<p id ="usl1"style="font-size:14px;display:none; font-family:tahoma; color:#000000; margin-left: 10px;">Услуги по подготовке и подаче заявки на регистрацию - <span id="uslugi1"></span> рублей</p>
<p style="font-size:14px; font-family:tahoma; color:#000000; margin-left: 10px;">Пошлины - <span id="poshlini"></span>  рублей</p>
<p style="display:none; font-size:14px; font-family:tahoma; color:#000000; margin-left: 10px;" id="pSpeedReg">Ускоренная регистрация - <span id="speedReg"></span>  рублей</p>
<p style="display:none; font-size:14px; font-family:tahoma; color:#000000; margin-left: 10px;" id="pPriceFind">Поиск сходных знаков  - <span id="priceFind"></span>  рублей</p>
<div style="display:none; font-size:14px; font-family:tahoma; color:#000000; margin-left: 10px;" id="pPriceFindComb">Поиск сходных знаков:<p style="font-size:14px; font-family:tahoma; color:#000000; margin-left: 10px;"> Словесный - <span id="priceFindSlov"></span>  рублей<p>
 <p style="font-size:14px; font-family:tahoma; color:#000000; margin-left: 10px;"> Изобразительный - <span id="priceFindIzob"></span>  рублей<p>
</div>

  </div>

<% end %>

app/views/application/request_form.html.erb
<%= form_for(@trademark) do |f| %>
  <% if @trademark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trademark.errors.count, "error") %> prohibited this trademark from being saved:</h2>

      <ul>
      <% @trademark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :research %><br />
    <%= f.check_box :research %>
  </div>
  <div class="field">
    <%= f.label :research_limit %><br />
    <%= f.text_field :research_limit %>
  </div>
  <div class="field">
    <%= f.label :registration_limit %><br />
    <%= f.text_field :registration_limit %>
  </div>
  <div class="field">
    <%= f.label :service %><br />
    <%= f.text_area :service %>
  </div>
  <div class="field">
    <%= f.label :mktu %><br />
    <%= f.text_field :mktu %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :requisites %><br />
    <%= f.text_area :requisites %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/index.html.erb
<% content_for :title do %>Статьи<% end %>

<% content_for :header_class do %>page-header_3<% end %>

<% content_for :content do %>
    <article class="entry">
       <h2 class="entry-title">Статьи</h2>
    </article><!-- /Entry -->

    <section class="news">
        <% @articles.each do |article| %>
            <article class="news-item">
                <h3 class="news-item-title"><%= link_to article.title, article %></h3>
                <footer class="news-item-date"><%= article.subtitle %></footer>
            </article>
        <% end %>
    </section>
<% end %>

app/views/articles/show.html.erb
<% content_for :title do %><%= @article.title.html_safe %><% end %>

<% content_for :header_class do %>page-header_3<% end %>

<% content_for :content do %>
    <p class="crumbs"><%= link_to 'Статьи', articles_path() %></p>

    <article class="entry">
       <h2 class="entry-title"><%= @article.title.html_safe %></h2>
        <%= @article.content.html_safe %>

        <% if @article.see_also.strip.length != 0 %>
            <section class="more">
                <h4 class="title more-title">Смотрите также:</h4>
                <%= @article.see_also.html_safe %>
            </section>
        <% end %>

    </article><!-- /Entry -->

<% end %>

app/views/news/index.html.erb
<% content_for :title do %>Новости<% end %>

<% content_for :header_class do %>page-header_3<% end %>

<% content_for :content do %>
    <article class="entry">
       <h2 class="entry-title">Новости</h2>
       <p>Наши специалисты дают комментарии и&nbsp;рассказывают о&nbsp;значимых событиях и&nbsp;изменениях в&nbsp;правовой сфере, а&nbsp;также деятельности компании.</p>
    </article><!-- /Entry -->

    <section class="news">
        <% @news.each do |news| %>
            <article class="news-item<% if news.of_company %>  news-item_company<% end %><% if news.special %>  news-item_special<% end %>">
                <h3 class="news-item-title"><%= link_to news.title.html_safe, news %><% if news.has_comment %> (с комментариями)<% end %></h3>
                <footer class="news-item-date"><% if news.of_company %>Новость компании, <% end %><%= l news.date, :format => '%d %B' %></footer>
            </article>
        <% end %>
    </section>
<% end %>

app/views/news/show.html.erb
<% content_for :title do %><%= @news.title.html_safe %><% end %>

<% content_for :header_class do %>page-header_3<% end %>

<% content_for :content do %>
    <p class="crumbs"><%= link_to 'Новости', '/news/' %></p>

    <article class="entry">
        <h2 class="entry-title"><%= @news.title.html_safe %></h2>
        <p><em><%= l @news.date, :format => '%d %B' %></em></p>

        <%= @news.content.html_safe %>

        <% if @news.has_comment %>
            <section class="note">
                <h3 class="title note-title">Комментарий нашего эксперта</h3>
                <%= @news.comment.html_safe %>
            </section>
        <% end %>

        <% if @news.has_see_also %>
            <section class="more">
                <h4 class="title more-title">Смотрите также:</h4>
                <%= @news.see_also.html_safe %>
            </section>
        <% end %>

    </article><!-- /Entry -->

    <div class="news_nav">
        <% if @news_next %>
            <div class="news_nav-prev">
                 <h4 class="title news_nav-title">Следующая новость:</h4>
                 <article class="news-item">
                    <h3 class="news-item-title"><%= link_to @news_next.title, @news_next %></h3>
                    <footer class="news-item-date"><%= l @news_next.date, :format => '%d %B' %></footer>
                 </article>
            </div>
        <% end %>
        <% if @news_prev %>
            <div class="news_nav-next">
                <h4 class="title news_nav-title">Предыдущая новость:</h4>
                <article class="news-item">
                    <h3 class="news-item-title"><%= link_to @news_prev.title, @news_prev %></h3>
                    <footer class="news-item-date"><%= l @news_prev.date, :format => '%d %B' %></footer>
                </article>
            </div>
        <% end %>
    </div>
<% end %>

app/views/questions/new.html.erb
<% content_for :title do %>Задать вопрос<% end %>

<% content_for :content do %>

<h2 class="entry-title">Задать вопрос</h2>

    <%= form_for @question do |f| %>

        <% if @question.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
              <ul>
              <% @question.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
        <% end %>

      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :message %><br />
        <%= f.text_area :message %>
      </div>
      <div class="actions">
        <input type="submit" value="Отправить вопрос" />
      </div>

    <% end %>


<% end %>

app/views/questions/success.html.erb
<% content_for :title do %>Вопрос успешно отправлен<% end %>

<% content_for :content do %>
    Вопрос успешно отправлен.
<% end %>

app/views/trademarks/success.html.erb
<% content_for :title do %>Заявка успешно отправлена<% end %>

<% content_for :content do %>
    Заявка успешно отправлена.
<% end %>