config/routes.rb
Project::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users
  resources :news, :only => [:index, :show]
  resources :articles, :only => [:index, :show]
  resources :questions, :only => [:new, :create]
  resources :trademarks, :only => [:new, :create]

  match "/calculator/" => "application#calculator_form", :as => 'calculator_form'
  match "/request/" => "trademarks#new", :as => 'request_form'
  match "/contact/" => "questions#new", :as => 'contact_form'
  match "/:slug/" => "pages#show"
  root :to => "pages#show"

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :subtitle, :content, :see_also
end

app/models/chunk.rb
class Chunk < ActiveRecord::Base
  attr_accessible :title, :code, :content, :visible
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/news.rb
class News < ActiveRecord::Base
  default_scope :order => 'date DESC'
  attr_accessible :title, :date, :content, :of_company, :special, :comment, :see_also

  def has_comment
    self.comment and self.comment.strip.length > 0
  end
  def has_see_also
    self.see_also and self.see_also.strip.length > 0
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :title, :slug, :content, :service, :info
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :name, :email, :message
end

app/models/trademark.rb
# -*- coding: utf-8 -*-
class Trademark < ActiveRecord::Base
  attr_accessible :title, :research, :research_limit, :registration_limit, :service, :mktu, :comments, :name, :requisites, :email, :phone, :contact, :title_image, :title_mixed, :requisites_file

  validates :registration_limit, :presence => true
  validates :service, :presence => true
  validates :name, :presence => true
  validates :requisites, :presence => true
  validates :email, :presence => true
  validates :phone, :presence => true
  validates :contact, :presence => true

  has_attached_file :title_image
  has_attached_file :title_mixed
  has_attached_file :requisites_file

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,# :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :email_notifications

  scope :emailable, where(:email_notifications => true)
end

app/controllers/application_controller.rb
# -*- coding: utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale, :set_context

  def set_context
    @news_all = News.where('of_company = False').limit(3)
    @news_company = News.where('of_company = True').limit(3)

    ['header_quote','header_phones','left_announce','left_in_process','left_clients','right_social','membership','footer_copyright','footer_phones','menu'].each do |var_name|
      chunk = Chunk.find_by_code(var_name)
      if chunk and chunk.visible
        chunk = chunk.content.html_safe
      else
        chunk = ''
      end
      self.instance_variable_set('@' + var_name, chunk)
    end

  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def calculator_form
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @news = News.find(params[:id])
    @news_prev = News.find(:first, :conditions => ["date < ?", @news.date])
    @news_next = News.find(:first, :conditions => ["date > ?", @news.date])

    respond_to do |format|
      format.html # show.html.erb
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find_by_slug(params[:slug] || '') || not_found

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions/new
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # POST /questions
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        User.emailable.each do |user|
          UserMailer.new_question(user, @question).deliver
        end
        format.html { render action: "success" }
      else
        format.html { render action: "new" }
      end
    end
  end

  def success
  end

end

app/controllers/trademarks_controller.rb
class TrademarksController < ApplicationController
  # GET /trademarks/new
  def new
    @trademark = Trademark.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # POST /trademarks
  def create
    @trademark = Trademark.new(params[:trademark])

    respond_to do |format|
      if @trademark.save
        User.emailable.each do |user|
          UserMailer.new_trademark(user, @trademark, request).deliver
        end
        format.html { render action: "success" }
      else
        format.html { render action: "new" }
      end
    end
  end

  def success
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chunks_helper.rb
module ChunksHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/trademarks_helper.rb
module TrademarksHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7 ]> <html class="ie ie6 no-js" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie ie7 no-js" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie ie8 no-js" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie ie9 no-js" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--><html class="no-js" lang="en"><!--<![endif]-->
<!-- the "no-js" class is for Modernizr. -->

<head id="zuykov.ru" data-template-set="html5-reset">
    <meta charset="utf-8">
    <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><%= yield :title %></title>
    <meta name="description" content="">
    <meta name="google-site-verification" content="">
    <link rel="shortcut icon" href="/i/favicon.ico">
    <link rel="stylesheet" href="/css/zuykov.css">
    <!-- Add fancyBox -->
    <link rel="stylesheet" href="/js/fancybox/jquery.fancybox.css?v=2.0.6" type="text/css" media="screen">
    <!-- all our JS is at the bottom of the page, except for Modernizr. -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script src="/js/modernizr-1.7.min.js"></script>
    <script src="/calc.js"></script>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body>
    <div class="page">
        <header class="page-header <%= yield :header_class %>" role="banner">
            <div class="page-header-logo"><a href="/"><img src="/i/logo.jpg" alt=""></a></div>
            <div class="clearfix">
                <div class="col_l">
                    <%= @header_quote %>
                </div>
                <div class="col_r">
                    <%= @header_phones %>
                </div>
            </div>

            <hr class="hr_dbl">

            <%= @menu %>
        </header><!-- /Page header -->

        <div class="page-content">
            <hr class="hr hr_dbl">

            <div class="columns clearfix">
                <div class="col_c">
                    <div class="content" role="main">
                        <p id="notice"><%= notice %></p>
                        <%= content_for?(:content) ? yield(:content) : yield %>
                    </div><!-- /Content -->
                </div><!-- /Column Center -->

                <div class="col_l">
                    <% if @left_announce.length > 0 %>
                        <article class="event">
                            <%= @left_announce %>
                        </article>
                    <% end %>

                    <section class="work">
                        <%= @left_in_process %>
                    </section>

                   <section class="clients">
                       <h2 class="title clients-title">Наши клиенты</h2>
                       <%= @left_clients %>
                       <p class="clients-all"><a href="/clients/">Все клиенты</a></p>
                   </section>
                </div><!-- /Column Left -->

                <div class="col_r">
                    <section class="service">
                       <p><%= link_to 'Расчет стоимости услуг', calculator_form_path %></p>
                       <p><%= link_to 'Заявка на регистрацию товарного знака', request_form_path %></p>
                       <p><%= link_to 'Задать вопрос', contact_form_path %></p>
                    </section>

                    <section class="news">
                       <h2 class="title news-title">Новости</h2>
                       <ul class="filter">
                           <li class="filter-item filter-item_act"><a href=""><span class="filter-item-txt">Рынок</span></a></li>
                           <li class="filter-item"><a href=""><span class="filter-item-txt">Компания</span></a></li>
                       </ul>

                       <div lcass="filter-container">
                           <div class="news-items">
                                <% @news_all.each do |news| %>
                                    <article class="news-item">
                                        <h3 class="news-item-title"><%= link_to news.title.html_safe, news %></h3>
                                        <footer class="news-item-date"><%= l news.date, :format => '%d %B' %></footer>
                                    </article>
                                <% end %>
                           </div>

                           <div class="news-items" style="display:none;">
                                <% @news_company.each do |news| %>
                                    <article class="news-item">
                                        <h3 class="news-item-title"><%= link_to news.title.html_safe, news %></h3>
                                        <footer class="news-item-date"><%= l news.date, :format => '%d %B' %></footer>
                                    </article>
                                <% end %>
                           </div>
                       </div>
                       <section class="social_news">
                           <h2 class="title social_news-title">Наши новости<br> в&nbsp;социальных сетях:</h2>
                           <%= @right_social %>
                           <p class="social_news-all"><a href="/news/">Архив новостей на сайте</a></p>
                       </section>
                    </section>
                </div><!-- /Column Right -->
            </div>

            <hr class="hr hr_dbl">

            <section class="membership">
                <h2 class="title membership-title">Членство в международных организациях</h2>
                <%= @membership %>
            </section>
        </div><!-- /Page content -->
    </div><!-- /Page -->

    <footer class="page-footer" role="contentinfo">
        <div class="clearfix">
            <div class="col_l">
                <%= @footer_copyright %>
                <p class="page-footer-nav"><a href="/contacts/">Контакты</a> <!-- a href="/job/">Вакансии</a --></p>
            </div>
            <div class="col_r">
                <%= @footer_phones %>
            </div>
        </div>
    </footer><!-- /Page footer -->


<!-- here comes the javascript -->

<!-- Add jQuery library -->
<script src="/js/jquery-1.7.2.min.js"></script>
<script src="/js/jquery.mousewheel-3.0.6.pack.js"></script>
<!-- Add fancyBox -->
<script src="/js/fancybox/jquery.fancybox.pack.js?v=2.0.6"></script>
<script>
    $(document).ready(function() {
        $(".fancybox").fancybox();

        var jMenuItem = $('a[href="<%= request.fullpath %>/"]').parent();
        if(jMenuItem.is('.nav_sub-item')) {
            jMenuItem.addClass('nav_sub-item_act');
            $(jMenuItem).html($('a', jMenuItem).html());
        } else if(jMenuItem.is('.nav-item')) {
            jMenuItem.addClass('nav-item_act');
        }

        //Tabs
        $(".filter a").click(function() {
            $(this).parent().siblings().removeClass('filter-item_act').end().addClass('filter-item_act');
            $(this).parents('.filter').next().children().hide().eq( $(this).parent().index() ).show();
            return false;
        });
    });
</script>


<!-- Asynchronous google analytics; this is the official snippet.
     Replace UA-XXXXXX-XX with your site's ID and uncomment to enable.

<script>

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-XXXXXX-XX']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
-->

</body>
</html>

app/views/pages/show.html.erb
<% content_for :title do %><%= @page.title.html_safe %><% end %>

<% content_for :header_class do %>
    <% if ['clients','trademarks','programs','patents','copyright'].include?(@page.slug) %>
        page-header_2
    <% elsif ['contacts','courts','contracts','forms'].include?(@page.slug) %>
        page-header_3
    <% end %>
<% end %>

<% content_for :content do %>
    <%= @page.content.html_safe %>

    <% if @page.service and @page.service.strip.length != 0 %>
        <section class="more">
            <h4 class="title more-title">Смежные услуги:</h4>
            <%= @page.service.html_safe %>
        </section>
    <% end %>

    <% if @page.info and @page.info.strip.length != 0 %>
        <section class="more">
            <h4 class="title more-title">Полезная информация:</h4>
            <%= @page.info.html_safe %>
        </section>
    <% end %>

<% end %>